// Shared ESLint flat-config base for every workspace. Extended by
// `./react.js` (which layers React/JSX plugins and browser globals for
// `**/*.{ts,tsx}` and `public/**/*.js`). Non-React packages import this
// module directly.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      'dist',
      'coverage',
      '.turbo',
      'node_modules',
      // Generated by `supabase gen types`; never hand-edited, never linted.
      '**/database.types.ts',
      // vitest bundles its config to a short-lived `*.timestamp-*.mjs`; when
      // turbo runs lint and test in parallel, eslint can enumerate the file
      // and then fail with ENOENT once vitest removes it.
      '**/*.timestamp-*.mjs',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  {
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.node },
      parserOptions: { projectService: true },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      'no-console': ['warn', { allow: ['warn', 'error'] }],

      // ── Type-aware rules (strictTypeChecked) — deliberate adjustments ──────
      // Stylistic: `onClick={() => setOpen(true)}` is idiomatic React; the
      // rule would demand braces on ~470 arrow callbacks for no safety gain.
      '@typescript-eslint/no-confusing-void-expression': 'off',
      // The Supabase client returns `{ data, error }` where `error` is a
      // PostgrestError shape, and the repo's error layer
      // (packages/shared/src/errors/parseSupabaseError.ts) is built to accept
      // non-Error shapes. `if (error) throw error;` is the intended pattern.
      '@typescript-eslint/only-throw-error': 'off',
      // `async (…) => { … }` without await is used to give handlers a uniform
      // Promise return type. Not a defect.
      '@typescript-eslint/require-await': 'off',
      // Numbers and booleans interpolate unambiguously; objects/arrays do not.
      '@typescript-eslint/restrict-template-expressions': [
        'error',
        { allowNumber: true, allowBoolean: true, allowNullish: false, allowAny: false },
      ],
      // RATCHET TARGETS — currently off, each is a follow-up in its own PR:
      //   no-unnecessary-condition (117 sites, many from noUncheckedIndexedAccess)
      //   no-non-null-assertion    (61 sites, e.g. `a.equipment!.id` after a filter)
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      // React event-handler attributes (`onSubmit={handleSubmit(fn)}`,
      // `onClick={asyncHandler}`) are the one place a Promise-returning function
      // is idiomatic where `void` is expected; rejections there surface through
      // the mutation `onError` → toast path. Every other position stays checked.
      '@typescript-eslint/no-misused-promises': [
        'error',
        { checksVoidReturn: { attributes: false } },
      ],
      // Everything else in strictTypeChecked stays at `error`, notably:
      //   no-floating-promises, no-misused-promises, await-thenable,
      //   no-unsafe-{assignment,return,member-access,call,argument}.
    },
  },
  {
    // Test files mock the Supabase client chain with `vi.fn()`; the resulting
    // shapes are `any` by construction and asserting on them is the point.
    files: ['**/__tests__/**', '**/*.test.{ts,tsx}', '**/test/**'],
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/unbound-method': 'off',
      // Its autofix stripped `as HTMLInputElement` casts that tsc requires on
      // Testing Library queries (observed 2026-09-10). Not worth the risk here.
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      // Tests deliberately reject with Supabase-shaped plain objects.
      '@typescript-eslint/prefer-promise-reject-errors': 'off',
      '@typescript-eslint/no-base-to-string': 'off',
      '@typescript-eslint/no-deprecated': 'off',
    },
  },
  {
    // Build/tooling files and loose browser scripts live outside the TS
    // project graph; lint them without type information instead of forcing
    // them into a tsconfig.
    files: [
      '**/*.config.{js,ts,mjs}',
      'eslint.config.js',
      'public/**/*.js',
      'scripts/**/*.{js,mjs}',
    ],
    ...tseslint.configs.disableTypeChecked,
  },
);
