-- ============================================================
-- Migration: stock_movements polymorphic order reference
-- ============================================================
-- Evolves the existing stock_movements table to support references to
-- BOTH key_orders and technical_orders without dual FK columns.
--
-- Strategy: discriminator column + drop existing FKs.
--
--   1. Drop existing FK constraints (order_id → orders, order_item_id → order_items).
--      The UUID columns are retained as plain opaque references.
--   2. Add order_kind text discriminator (NULL | 'key' | 'technical').
--   3. Add CHECK: whenever order_id or order_item_id is set, order_kind must
--      also be set (no orphan references without context).
--   4. Add index for cross-context reservation lookups.
--
-- Design decision (D2): discriminator on stock_movements, dual FK on tickets.
-- stock_movements is an append-only ledger; referential integrity matters less
-- than schema simplicity. Orphan detection is a periodic audit query (see §12 R3).
--
-- Depends on: 20260818000081 (key_orders), 20260818000082 (technical_orders)

-- 1. Drop existing FK constraints.
--    Constraint names match those generated by PostgreSQL from the table DDL
--    in 20260811000029_create_stock_movements_table.sql.
alter table public.stock_movements
  drop constraint if exists stock_movements_order_id_fkey;
alter table public.stock_movements
  drop constraint if exists stock_movements_order_item_id_fkey;

-- 2. Add the discriminator column.
alter table public.stock_movements
  add column order_kind text null
    check (order_kind is null or order_kind in ('key', 'technical'));

-- 3. Enforce discriminator presence whenever any order reference exists.
--    NULL order_id + NULL order_item_id + NULL order_kind = non-order movement (allowed).
--    Any order reference without order_kind = invalid (rejected).
alter table public.stock_movements
  add constraint stock_movements_order_kind_required check (
    (order_id is null and order_item_id is null and order_kind is null)
    or (order_kind is not null)
  );

-- 4. Index for cross-context reservation lookups by (order_kind, order_id).
create index stock_movements_order_kind_order_id_idx
  on public.stock_movements (order_kind, order_id)
  where order_id is not null;
